CREATE TABLE IF NOT EXISTS USER_INFO (
    ID SERIAL PRIMARY KEY,
    USER_ID VARCHAR(100) NOT NULL,
    USER_NAME VARCHAR(255),
    USER_EMAIL VARCHAR(255),
    CREATE_TIME TIMESTAMP NOT NULL,
    UPDATE_TIME TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS IDX_USER_INFO_USER_ID ON USER_INFO(USER_ID); 